apiVersion: apps/v1
kind: Deployment

metadata:
  name: banking-frontend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: banking-frontend

  template:
    metadata:
      labels:
        app: banking-frontend

    spec:
      containers:
        - name: banking-frontend

          image: banking-frontend:latest

          imagePullPolicy: Never

          ports:
            - containerPort: 3000
