{
  "apiVersion": "kustomize.config.k8s.io/v1beta1",
  "kind": "Kustomization",
  "namespace": "banking-production",
  "resources": [
    "../../base"
  ],
  "images": [
    {
      "name": "ghcr.io/kmdsuhail72/banking-backend",
      "digest": "sha256:0000000000000000000000000000000000000000000000000000000000000000"
    }
  ],
  "replicas": [
    {
      "name": "banking-backend",
      "count": 0
    }
  ]
}
