apiVersion: v1
kind: Secret
metadata:
  name: banking-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "banking.labels" . | nindent 4 }}
type: Opaque
stringData:
  # TODO: In production, use External Secrets Operator or Sealed Secrets
  # to inject these from AWS Secrets Manager / Vault instead of values.
  postgres-dsn: "postgresql://{{ .Values.global.postgres.user }}:change-me-db-password@{{ .Values.global.postgres.host }}:{{ .Values.global.postgres.port }}/{{ .Values.global.postgres.database }}"
  postgres-password: "change-me-db-password"
  jwt-secret: "change-me-in-production"
  jwt-refresh-secret: "change-me-refresh-in-production"

